# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.8'

services:
  redisdb:
    image: redis
    container_name: redisdb
    ports:
      - 6379:6379

  dotnetredisapi:
    image: dotnetredisapi
    build:
      context: .
      dockerfile: src/Dotnet_Redis.API/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:RedisDbConnectionString=redisdb"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - redis
