# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.8'

services:
  redisdb:
    image: redis
    container_name: redisdb
    ports:
      - 6379:6379

  dotnetredisapi:
    image: dotnetredisapi
    container_name: dotnetredisapi
    build:
      context: .
      dockerfile: src/Dotnet_Redis.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings:RedisDbConnectionString=redisdb"
    ports:
      - 5001:80
    depends_on:
      - redisdb
